-- MySQL Script generated by MySQL Workbench
-- Thu Jan 16 20:57:10 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema CarDealership
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema CarDealership
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `CarDealership` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `CarDealership` ;

-- -----------------------------------------------------
-- Table `CarDealership`.`Car`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CarDealership`.`Car` ;

CREATE TABLE IF NOT EXISTS `CarDealership`.`Car` (
  `CarID` INT NOT NULL AUTO_INCREMENT,
  `Color` VARCHAR(30) NULL DEFAULT NULL,
  `Make` VARCHAR(50) NULL DEFAULT NULL,
  `Model` VARCHAR(50) NULL DEFAULT NULL,
  `Price` DECIMAL(10,2) NULL DEFAULT NULL,
  `Status` VARCHAR(20) NULL DEFAULT NULL,
  `Year` INT NULL DEFAULT NULL,
  PRIMARY KEY (`CarID`))
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `CarDealership`.`Customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CarDealership`.`Customer` ;

CREATE TABLE IF NOT EXISTS `CarDealership`.`Customer` (
  `CustomerID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(100) NULL DEFAULT NULL,
  `Address` VARCHAR(255) NULL DEFAULT NULL,
  `ContactInfo` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`CustomerID`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `CarDealership`.`Sales`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CarDealership`.`Sales` ;

CREATE TABLE IF NOT EXISTS `CarDealership`.`Sales` (
  `SalesID` INT NOT NULL AUTO_INCREMENT,
  `CarID` INT NOT NULL,
  `CustomerID` INT NOT NULL,
  `SalesDate` DATE NULL DEFAULT NULL,
  `SalesPrice` DECIMAL(10,2) NULL DEFAULT NULL,
  PRIMARY KEY (`SalesID`),
  INDEX `CarID` (`CarID` ASC) VISIBLE,
  INDEX `CustomerID` (`CustomerID` ASC) VISIBLE,
  CONSTRAINT `sales_ibfk_1`
    FOREIGN KEY (`CarID`)
    REFERENCES `CarDealership`.`Car` (`CarID`)
    ON DELETE CASCADE,
  CONSTRAINT `sales_ibfk_2`
    FOREIGN KEY (`CustomerID`)
    REFERENCES `CarDealership`.`Customer` (`CustomerID`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
